title: Blog de DDD Madrid
description: > # this means to ignore newlines until "baseurl:"
  Este es el blog de la comunidad de DDD Madrid. Quieres escribir algo relacionado
  con DDD? Este es tu sitio :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dddmadrid
github_username:  dddmadrid
google_analytics: UA-98701345-1
disqus:
  shortname: disqus_dB3ps0QeQV 
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
